### ISSUE TITLE
M2_Encoder python run.py output TypeError: parse_dict() got an unexpected keyword argument 'allow_extra_keys'

### ISSUE THREAD

**Issue by smtrnd** [alipay/Ant-Multi-Modal-Framework#11]
Traceback (most recent call last):
  File "run.py", line 16, in <module>
    encoder.warmup_local_model()
  File "/root/anaconda3/envs/m2-encoder/lib/python3.8/site-packages/nn4k/invoker/base.py", line 191, in warmup_local_mod
el
    model_args, *_ = parser.parse_dict(self.init_args, allow_extra_keys=True)
TypeError: parse_dict() got an unexpected keyword argument 'allow_extra_keys'

**Comment by smtrnd** [comment]
run:
conda install conda-forge::transformers
pip install chardet
output AssertionError: either nn_name or nn_model_path has to be provided When running M2-Encode

**Comment by xinglzlz** [comment]
same issue

**Comment by HanxiaoZhang** [comment]
@smtrnd @xinglzlz This issue can be resolved by installing a specific version using the command: `pip install openspg-nn4k==0.0.2b3`. We have already fixed it. [https://github.com/alipay/Ant-Multi-Modal-Framework/blob/a6b512902b0e4d4721886e8751b8dcd5721f18d5/prj/M2_Encoder/requirements.txt#L24](url)
