### ISSUE TITLE
Inquiry about Model Size and Plans for Open Sourcing Larger Models

### ISSUE THREAD

**Issue by 209ye** [alipay/Ant-Multi-Modal-Framework#3]
Hello, I noticed that the model in Modelscope is m2_encoder_0.2B.ckpt. Is this the 0.4B parameter model mentioned in the paper? Will there be larger models open sourced in the future?

**Comment by LandyGuo** [comment]
fixe the issue in this commit: https://github.com/alipay/Ant-Multi-Modal-Framework/commit/b38e199ecca0989c84fcba49f44823a1024a14a7, and naming in modelscope: https://www.modelscope.cn/models/M2Cognition/M2-Encoder/files

**Comment by 209ye** [comment]
Thanks for the detailed response and sharing your future plans. I'm excited to hear about your team's intention to open source models at the 1 billion and 10 billion parameter scale. Appreciate your contributions through open sourcing valuable AI resources.
