### ISSUE TITLE
Any plan to use M2-Encoder to make better text-video retrieval?

### ISSUE THREAD

**Issue by hujunchao** [alipay/Ant-Multi-Modal-Framework#5]
Congratulations on training such a great model！Is there any plan to use M2-Encoder to make better text-video retrieval?

**Comment by LandyGuo** [comment]
Yes, welcome to follow our work on M2-RAAP(SIGIR-24): https://github.com/alipay/Ant-Multi-Modal-Framework/tree/main/prj/M2_RAAP, code & models will be released soon.
