### ISSUE TITLE
Zero-shot accuracy on ImageNet (in the CLIP setting) is lower than the number reported in the paper

### ISSUE THREAD

**Issue by shyammarjit** [alipay/Ant-Multi-Modal-Framework#6]
## Zero-shot accuracy on ImageNet (in the CLIP setting)
Top-1 accuracy: 77.15
Top-5 accuracy: 95.51

## Paper reported accuracy on ImageNet is (Top-1): 88.5

**Comment by 209ye** [comment]
The 88.5 accuracy mentioned in the paper here should be the 10B model, which seems to have not been announced yet. The published 0.4b model looks at the data in the paper and is (Top-1) 78.5.

**Comment by shyammarjit** [comment]
How do I load the 10B model? Is it open-sourced yet?

**Comment by LandyGuo** [comment]
> How do I load the 10B model? Is it open-sourced yet?

 All models are released here: https://www.modelscope.cn/organization/M_Square. Meanwhile, we provide a simple example at https://github.com/alipay/Ant-Multi-Modal-Framework/blob/main/prj/M2_Encoder/run.py. By modifying cfg['model_config'], you can switch to different-sized models.

**Comment by shyammarjit** [comment]
Thank you.
